In [3]:
#pip install beautifulsoup4

from bs4 import BeautifulSoup

In [4]:
with open("index.html", encoding='utf8') as f:
    html_doc = f.read()

soup = BeautifulSoup(html_doc, 'html.parser')
print(soup.prettify())

<!DOCTYPE html>
<html>
 <head>
  <title>
   My Simple Webpage
  </title>
 </head>
 <body>
  <h1>
   Welcome to My Webpage
  </h1>
  <p>
   This is a paragraph of text on my webpage.
  </p>
  <p>
   Here's a list:
  </p>
  <ul>
   <li id="item1">
    Item 1
   </li>
   <li>
    Item 2
   </li>
   <li>
    Item 3
   </li>
  </ul>
  <p>
   Visit
   <a href="https://example.com">
    Example.com
   </a>
   .
  </p>
 </body>
</html>

In [5]:
# Mengambil satu elemen spesifik
var = soup.find(id='item1')
print('=====')
print(var)
print('=====')
print(var.text)
print('=====')
print(var.name)
print('=====')
print(var.parent)
print('=====')
print(var.child)
print('=====')

=====
<li id="item1">Item 1</li>
=====
Item 1
=====
li
=====
<ul>
<li id="item1">Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
=====
None
=====

In [6]:
var2 = soup.find('ul')

print('=====')
print(var2)
print('=====')
print(var2.text)
print('=====')
print(var2.name)
print('=====')
print(var2.parent)
print('=====')
print(var2.child)
print('=====')

=====
<ul>
<li id="item1">Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
=====

Item 1
Item 2
Item 3

=====
ul
=====
<body>
<h1>Welcome to My Webpage</h1>
<p>This is a paragraph of text on my webpage.</p>
<p>Here's a list:</p>
<ul>
<li id="item1">Item 1</li>
<li>Item 2</li>
<li>Item 3</li>
</ul>
<p>Visit <a href="https://example.com">Example.com</a>.</p>
</body>
=====
None
=====

In [7]:
# Mengambil beberapa elemen sekaligus
for i, p in enumerate(soup.find_all("p"), start=1):
    print(f"Element ke-{i}:")
    print(p)
    print("----")
    print(p.text)
    print("====")

Element ke-1:
<p>This is a paragraph of text on my webpage.</p>
----
This is a paragraph of text on my webpage.
====
Element ke-2:
<p>Here's a list:</p>
----
Here's a list:
====
Element ke-3:
<p>Visit <a href="https://example.com">Example.com</a>.</p>
----
Visit Example.com.
====

In [8]:
import requests # untuk meminta/mengambil kode html dari halaman web
from bs4 import BeautifulSoup

url = "https://quotes.toscrape.com/"
html = requests.get(url).text

soup_quotes = BeautifulSoup(html, 'html.parser')
quotes = soup_quotes.find_all('span', class_="text")

for i, q in enumerate(quotes, start=1):
    print(f'Quote ke-{i}: {q.text}')

Quote ke-1: “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
Quote ke-2: “It is our choices, Harry, that show what we truly are, far more than our abilities.”
Quote ke-3: “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
Quote ke-4: “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
Quote ke-5: “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
Quote ke-6: “Try not to become a man of success. Rather become a man of value.”
Quote ke-7: “It is better to be hated for what you are than to be loved for what you are not.”
Quote ke-8: “I have not failed. I've just found 10,000 ways that won't work.”
Quote ke-9: “A woman is like a tea bag; you never know how strong it is until it's in hot water.”
Quote ke-10: “A day without sunshine is like, you know, night.”

In [9]:
soup_author = BeautifulSoup(html, 'html.parser')
author = soup_author.find_all('small', class_="author")

for i, q in enumerate(author, start=1):
    print(f'author-{i}: {q.text}')

author-1: Albert Einstein
author-2: J.K. Rowling
author-3: Albert Einstein
author-4: Jane Austen
author-5: Marilyn Monroe
author-6: Albert Einstein
author-7: André Gide
author-8: Thomas A. Edison
author-9: Eleanor Roosevelt
author-10: Steve Martin

In [10]:
soup_tag = BeautifulSoup(html, 'html.parser')
tag = soup_tag.find_all('div', class_="tags")

for i, q in enumerate(tag, start=1):
    print(f'author-{i}: {q.text}')

author-1:
            Tags:

change
deep-thoughts
thinking
world

author-2:
            Tags:

abilities
choices

author-3:
            Tags:

inspirational
life
live
miracle
miracles

author-4:
            Tags:

aliteracy
books
classic
humor

author-5:
            Tags:

be-yourself
inspirational

author-6:
            Tags:

adulthood
success
value

author-7:
            Tags:

life
love

author-8:
            Tags:

edison
failure
inspirational
paraphrased

author-9:
            Tags:

misattributed-eleanor-roosevelt

author-10:
            Tags:

humor
obvious
simile

In [11]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. Ambil HTML dari website
url = "https://quotes.toscrape.com/"
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")

# 2. Temukan semua blok quote
quote_blocks = soup.find_all("div", class_="quote")

# 3. Simpan hasil scraping ke list
data = []

for qb in quote_blocks:
    quote_text = qb.find("span", class_="text").get_text(strip=True)
    author_name = qb.find("small", class_="author").get_text(strip=True)

    data.append({
        "author": author_name,
        "quote": quote_text
    })

# 4. Buat DataFrame
df = pd.DataFrame(data)

df

              author                                              quote
0    Albert Einstein  “The world as we have created it is a process ...
1       J.K. Rowling  “It is our choices, Harry, that show what we t...
2    Albert Einstein  “There are only two ways to live your life. On...
3        Jane Austen  “The person, be it gentleman or lady, who has ...
4     Marilyn Monroe  “Imperfection is beauty, madness is genius and...
5    Albert Einstein  “Try not to become a man of success. Rather be...
6         André Gide  “It is better to be hated for what you are tha...
7   Thomas A. Edison  “I have not failed. I've just found 10,000 way...
8  Eleanor Roosevelt  “A woman is like a tea bag; you never know how...
9       Steve Martin  “A day without sunshine is like, you know, nig...

In [27]:
import requests
import pandas as pd 
from bs4 import BeautifulSoup

url = 'https://realpython.github.io/fake-jobs/'
response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')
lowongan_block = soup.find_all('div', class_='media-content')

data = []

for i, q in enumerate(lowongan_block, start=1):
    lowongan = q.find('h2', class_='title').get_text(strip=True)
    perusahaan = q.find('h3', class_='subtitle').get_text(strip=True)
    data.append({
        'Nama Posisi' : lowongan,
        'Perusahaan' : perusahaan
    })

df = pd.DataFrame(data)
df

                           Nama Posisi                  Perusahaan
0              Senior Python Developer    Payne, Roberts and Davis
1                      Energy engineer            Vasquez-Davidson
2                      Legal executive  Jackson, Chambers and Levy
3               Fitness centre manager              Savage-Bradley
4                      Product manager                 Ramirez Inc
..                                 ...                         ...
95  Museum/gallery exhibitions officer     Nguyen, Yoder and Petty
96            Radiographer, diagnostic                  Holder LLC
97              Database administrator              Yates-Ferguson
98                  Furniture designer             Ortega-Lawrence
99                         Ship broker   Fuentes, Walls and Castro

[100 rows x 2 columns]

In [63]:
print(soup_quotes.prettify())

<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Quotes to Scrape
  </title>
  <link href="/static/bootstrap.min.css" rel="stylesheet"/>
  <link href="/static/main.css" rel="stylesheet"/>
 </head>
 <body>
  <div class="container">
   <div class="row header-box">
    <div class="col-md-8">
     <h1>
      <a href="/" style="text-decoration: none">
       Quotes to Scrape
      </a>
     </h1>
    </div>
    <div class="col-md-4">
     <p>
      <a href="/login">
       Login
      </a>
     </p>
    </div>
   </div>
   <div class="row">
    <div class="col-md-8">
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="change,deep-thoughts,thinking,world" itemprop="keywords"/>
       <a class="tag" href="/tag/change/page/1/">
        change
       </a>
       <a class="tag" href="/tag/deep-thoughts/page/1/">
        deep-thoughts
       </a>
       <a class="tag" href="/tag/thinking/page/1/">
        thinking
       </a>
       <a class="tag" href="/tag/world/page/1/">
        world
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “It is our choices, Harry, that show what we truly are, far more than our abilities.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        J.K. Rowling
       </small>
       <a href="/author/J-K-Rowling">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="abilities,choices" itemprop="keywords"/>
       <a class="tag" href="/tag/abilities/page/1/">
        abilities
       </a>
       <a class="tag" href="/tag/choices/page/1/">
        choices
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="inspirational,life,live,miracle,miracles" itemprop="keywords"/>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
       <a class="tag" href="/tag/life/page/1/">
        life
       </a>
       <a class="tag" href="/tag/live/page/1/">
        live
       </a>
       <a class="tag" href="/tag/miracle/page/1/">
        miracle
       </a>
       <a class="tag" href="/tag/miracles/page/1/">
        miracles
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Jane Austen
       </small>
       <a href="/author/Jane-Austen">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="aliteracy,books,classic,humor" itemprop="keywords"/>
       <a class="tag" href="/tag/aliteracy/page/1/">
        aliteracy
       </a>
       <a class="tag" href="/tag/books/page/1/">
        books
       </a>
       <a class="tag" href="/tag/classic/page/1/">
        classic
       </a>
       <a class="tag" href="/tag/humor/page/1/">
        humor
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Marilyn Monroe
       </small>
       <a href="/author/Marilyn-Monroe">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="be-yourself,inspirational" itemprop="keywords"/>
       <a class="tag" href="/tag/be-yourself/page/1/">
        be-yourself
       </a>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “Try not to become a man of success. Rather become a man of value.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Albert Einstein
       </small>
       <a href="/author/Albert-Einstein">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="adulthood,success,value" itemprop="keywords"/>
       <a class="tag" href="/tag/adulthood/page/1/">
        adulthood
       </a>
       <a class="tag" href="/tag/success/page/1/">
        success
       </a>
       <a class="tag" href="/tag/value/page/1/">
        value
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “It is better to be hated for what you are than to be loved for what you are not.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        André Gide
       </small>
       <a href="/author/Andre-Gide">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="life,love" itemprop="keywords"/>
       <a class="tag" href="/tag/life/page/1/">
        life
       </a>
       <a class="tag" href="/tag/love/page/1/">
        love
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “I have not failed. I've just found 10,000 ways that won't work.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Thomas A. Edison
       </small>
       <a href="/author/Thomas-A-Edison">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="edison,failure,inspirational,paraphrased" itemprop="keywords"/>
       <a class="tag" href="/tag/edison/page/1/">
        edison
       </a>
       <a class="tag" href="/tag/failure/page/1/">
        failure
       </a>
       <a class="tag" href="/tag/inspirational/page/1/">
        inspirational
       </a>
       <a class="tag" href="/tag/paraphrased/page/1/">
        paraphrased
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “A woman is like a tea bag; you never know how strong it is until it's in hot water.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Eleanor Roosevelt
       </small>
       <a href="/author/Eleanor-Roosevelt">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="misattributed-eleanor-roosevelt" itemprop="keywords"/>
       <a class="tag" href="/tag/misattributed-eleanor-roosevelt/page/1/">
        misattributed-eleanor-roosevelt
       </a>
      </div>
     </div>
     <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text">
       “A day without sunshine is like, you know, night.”
      </span>
      <span>
       by
       <small class="author" itemprop="author">
        Steve Martin
       </small>
       <a href="/author/Steve-Martin">
        (about)
       </a>
      </span>
      <div class="tags">
       Tags:
       <meta class="keywords" content="humor,obvious,simile" itemprop="keywords"/>
       <a class="tag" href="/tag/humor/page/1/">
        humor
       </a>
       <a class="tag" href="/tag/obvious/page/1/">
        obvious
       </a>
       <a class="tag" href="/tag/simile/page/1/">
        simile
       </a>
      </div>
     </div>
     <nav>
      <ul class="pager">
       <li class="next">
        <a href="/page/2/">
         Next
         <span aria-hidden="true">
          →
         </span>
        </a>
       </li>
      </ul>
     </nav>
    </div>
    <div class="col-md-4 tags-box">
     <h2>
      Top Ten tags
     </h2>
     <span class="tag-item">
      <a class="tag" href="/tag/love/" style="font-size: 28px">
       love
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/inspirational/" style="font-size: 26px">
       inspirational
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/life/" style="font-size: 26px">
       life
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/humor/" style="font-size: 24px">
       humor
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/books/" style="font-size: 22px">
       books
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/reading/" style="font-size: 14px">
       reading
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/friendship/" style="font-size: 10px">
       friendship
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/friends/" style="font-size: 8px">
       friends
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/truth/" style="font-size: 8px">
       truth
      </a>
     </span>
     <span class="tag-item">
      <a class="tag" href="/tag/simile/" style="font-size: 6px">
       simile
      </a>
     </span>
    </div>
   </div>
  </div>
  <footer class="footer">
   <div class="container">
    <p class="text-muted">
     Quotes by:
     <a href="https://www.goodreads.com/quotes">
      GoodReads.com
     </a>
    </p>
    <p class="copyright">
     Made with
     <span class="zyte">
      ❤
     </span>
     by
     <a class="zyte" href="https://www.zyte.com">
      Zyte
     </a>
    </p>
   </div>
  </footer>
 </body>
</html>