In [27]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import logging 
import time 

logging.basicConfig(
    level = logging.INFO,
    format= '%(asctime)s | %(name)s | %(levelname)s | %(message)s',
    handlers=[
        logging.FileHandler('scraping_uhuy.log', encoding='utf-8'), # ke file
        logging.StreamHandler()                                     # ke layar notebook
    ]
)

logger = logging.getLogger('book_scraper')
base_url = 'https://books.toscrape.com'
rating_map = {'One':1, 'Two':2, 'Three':3, 'Four':4, 'Five':5}

def fetch_page(page):
    if page == 1 :
        url = base_url
    else :
        url = f'{base_url}/catalogue/page-{page}.html'
    
    #pakai try except supaya tidak berhenti jika ada satu halaman yg gagal
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        response.encoding = 'utf-8'
        return response 
    except requests.RequestException as e :
        logger.error(f'Gagal ambil halaman {page} : {e}') #bedanya kalo pakai logging maka akan muncul 'Root' bukan nama loggernya
        return None
     
def parse_book(response):
    soup = BeautifulSoup(response.text, 'html.parser')
    books = soup.find_all('article', class_='product_pod')
    result = []
    for book in books :
        title = book.h3.a.get('title')
        rating = book.find('p', class_='star-rating')['class'][1]
        harga = book.find('p', class_='price_color').get_text(strip=True)
        stok = book.find('p', class_='instock availability').get_text(strip=True)
        img_relatif = book.find('img')['src']
        img_url = urljoin(response.url,img_relatif)
        result.append({
            'Title' : title,
            'Rating' : rating,
            'Price' : harga,
            'Stok' : stok,
            'Link Image' : img_url
        })
    return result

def scrape_all(total_page, delay):
    summary = []
    for page in range(1, total_page + 1):
        response = fetch_page(page)
        if response is None:
            continue 
        summary.extend(parse_book(response))
        logger.info(f'Selesai halaman {page}. Total {len(summary)} buku')
        time.sleep(delay)
    logger.info(f'Semua buku telah di-scraping. Total {len(summary)} buku')
    return summary

def cleaning_data(df):
    df_clean = df.copy()
    df_clean['Price'] = df_clean['Price'].str.replace('£','',regex=False).astype(float)
    df_clean['Rating'] = df_clean['Rating'].map(rating_map)
    return df_clean

def run_pipeline(total_page=50, delay=0.5):
    summary = scrape_all(total_page,delay)
    df = pd.DataFrame(summary)
    df_clean = cleaning_data(df)
    return df_clean

df = run_pipeline()

2026-10-22 05:59:25,477 | book_scraper | INFO | Selesai halaman 1. Total 20 buku
2026-10-22 05:59:27,542 | book_scraper | INFO | Selesai halaman 2. Total 40 buku
2026-10-22 05:59:29,703 | book_scraper | INFO | Selesai halaman 3. Total 60 buku
2026-10-22 05:59:31,992 | book_scraper | INFO | Selesai halaman 4. Total 80 buku
2026-10-22 05:59:34,101 | book_scraper | INFO | Selesai halaman 5. Total 100 buku
2026-10-22 05:59:36,242 | book_scraper | INFO | Selesai halaman 6. Total 120 buku
2026-10-22 05:59:38,541 | book_scraper | INFO | Selesai halaman 7. Total 140 buku
2026-10-22 05:59:40,642 | book_scraper | INFO | Selesai halaman 8. Total 160 buku
2026-10-22 05:59:42,906 | book_scraper | INFO | Selesai halaman 9. Total 180 buku
2026-10-22 05:59:45,034 | book_scraper | INFO | Selesai halaman 10. Total 200 buku
2026-10-22 05:59:47,612 | book_scraper | INFO | Selesai halaman 11. Total 220 buku
2026-10-22 05:59:50,006 | book_scraper | INFO | Selesai halaman 12. Total 240 buku
2026-10-22 05:59:52,227 | book_scraper | INFO | Selesai halaman 13. Total 260 buku
2026-10-22 05:59:54,306 | book_scraper | INFO | Selesai halaman 14. Total 280 buku
2026-10-22 05:59:56,408 | book_scraper | INFO | Selesai halaman 15. Total 300 buku
2026-10-22 05:59:58,553 | book_scraper | INFO | Selesai halaman 16. Total 320 buku
2026-10-22 06:00:00,712 | book_scraper | INFO | Selesai halaman 17. Total 340 buku
2026-10-22 06:00:02,867 | book_scraper | INFO | Selesai halaman 18. Total 360 buku
2026-10-22 06:00:05,007 | book_scraper | INFO | Selesai halaman 19. Total 380 buku
2026-10-22 06:00:07,047 | book_scraper | INFO | Selesai halaman 20. Total 400 buku
2026-10-22 06:00:09,500 | book_scraper | INFO | Selesai halaman 21. Total 420 buku
2026-10-22 06:00:11,885 | book_scraper | INFO | Selesai halaman 22. Total 440 buku
2026-10-22 06:00:14,036 | book_scraper | INFO | Selesai halaman 23. Total 460 buku
2026-10-22 06:00:16,198 | book_scraper | INFO | Selesai halaman 24. Total 480 buku
2026-10-22 06:00:18,327 | book_scraper | INFO | Selesai halaman 25. Total 500 buku
2026-10-22 06:00:20,479 | book_scraper | INFO | Selesai halaman 26. Total 520 buku
2026-10-22 06:00:22,681 | book_scraper | INFO | Selesai halaman 27. Total 540 buku
2026-10-22 06:00:24,882 | book_scraper | INFO | Selesai halaman 28. Total 560 buku
2026-10-22 06:00:27,034 | book_scraper | INFO | Selesai halaman 29. Total 580 buku
2026-10-22 06:00:29,234 | book_scraper | INFO | Selesai halaman 30. Total 600 buku
2026-10-22 06:00:31,392 | book_scraper | INFO | Selesai halaman 31. Total 620 buku
2026-10-22 06:00:33,478 | book_scraper | INFO | Selesai halaman 32. Total 640 buku
2026-10-22 06:00:35,626 | book_scraper | INFO | Selesai halaman 33. Total 660 buku
2026-10-22 06:00:37,781 | book_scraper | INFO | Selesai halaman 34. Total 680 buku
2026-10-22 06:00:39,935 | book_scraper | INFO | Selesai halaman 35. Total 700 buku
2026-10-22 06:00:42,078 | book_scraper | INFO | Selesai halaman 36. Total 720 buku
2026-10-22 06:00:44,228 | book_scraper | INFO | Selesai halaman 37. Total 740 buku
2026-10-22 06:00:46,282 | book_scraper | INFO | Selesai halaman 38. Total 760 buku
2026-10-22 06:00:48,429 | book_scraper | INFO | Selesai halaman 39. Total 780 buku
2026-10-22 06:00:50,574 | book_scraper | INFO | Selesai halaman 40. Total 800 buku
2026-10-22 06:00:52,740 | book_scraper | INFO | Selesai halaman 41. Total 820 buku
2026-10-22 06:00:54,876 | book_scraper | INFO | Selesai halaman 42. Total 840 buku
2026-10-22 06:00:57,053 | book_scraper | INFO | Selesai halaman 43. Total 860 buku
2026-10-22 06:00:59,387 | book_scraper | INFO | Selesai halaman 44. Total 880 buku
2026-10-22 06:01:01,826 | book_scraper | INFO | Selesai halaman 45. Total 900 buku
2026-10-22 06:01:04,629 | book_scraper | INFO | Selesai halaman 46. Total 920 buku
2026-10-22 06:01:06,762 | book_scraper | INFO | Selesai halaman 47. Total 940 buku
2026-10-22 06:01:09,028 | book_scraper | INFO | Selesai halaman 48. Total 960 buku
2026-10-22 06:01:11,264 | book_scraper | INFO | Selesai halaman 49. Total 980 buku
2026-10-22 06:01:13,422 | book_scraper | INFO | Selesai halaman 50. Total 1000 buku
2026-10-22 06:01:13,923 | book_scraper | INFO | Semua buku telah di-scraping. Total 1000 buku

In [28]:
#testing fetch_page
response = fetch_page(1)
response

In [29]:
#testing parse_book
response = fetch_page(1)
data = parse_book(response)
print(len(data))

20

In [30]:
#testing scrape_all 1 page
summary= scrape_all(1,0.5)
summary

2026-10-22 06:11:34,989 | book_scraper | INFO | Selesai halaman 1. Total 20 buku
2026-10-22 06:11:35,491 | book_scraper | INFO | Semua buku telah di-scraping. Total 20 buku

[{'Title': 'A Light in the Attic',
  'Rating': 'Three',
  'Price': '£51.77',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg'},
 {'Title': 'Tipping the Velvet',
  'Rating': 'One',
  'Price': '£53.74',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg'},
 {'Title': 'Soumission',
  'Rating': 'One',
  'Price': '£50.10',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg'},
 {'Title': 'Sharp Objects',
  'Rating': 'Four',
  'Price': '£47.82',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg'},
 {'Title': 'Sapiens: A Brief History of Humankind',
  'Rating': 'Five',
  'Price': '£54.23',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg'},
 {'Title': 'The Requiem Red',
  'Rating': 'One',
  'Price': '£22.65',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg'},
 {'Title': 'The Dirty Little Secrets of Getting Your Dream Job',
  'Rating': 'Four',
  'Price': '£33.34',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg'},
 {'Title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'Rating': 'Three',
  'Price': '£17.93',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg'},
 {'Title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Rating': 'Four',
  'Price': '£22.60',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/66/88/66883b91f6804b2323c8369331cb7dd1.jpg'},
 {'Title': 'The Black Maria',
  'Rating': 'One',
  'Price': '£52.15',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/58/46/5846057e28022268153beff6d352b06c.jpg'},
 {'Title': 'Starving Hearts (Triangular Trade Trilogy, #1)',
  'Rating': 'Two',
  'Price': '£13.99',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/be/f4/bef44da28c98f905a3ebec0b87be8530.jpg'},
 {'Title': "Shakespeare's Sonnets",
  'Rating': 'Four',
  'Price': '£20.66',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/10/48/1048f63d3b5061cd2f424d20b3f9b666.jpg'},
 {'Title': 'Set Me Free',
  'Rating': 'Five',
  'Price': '£17.46',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/5b/88/5b88c52633f53cacf162c15f4f823153.jpg'},
 {'Title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'Rating': 'Five',
  'Price': '£52.29',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/94/b1/94b1b8b244bce9677c2f29ccc890d4d2.jpg'},
 {'Title': 'Rip it Up and Start Again',
  'Rating': 'Five',
  'Price': '£35.02',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/81/c4/81c4a973364e17d01f217e1188253d5e.jpg'},
 {'Title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Rating': 'Three',
  'Price': '£57.25',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/54/60/54607fe8945897cdcced0044103b10b6.jpg'},
 {'Title': 'Olio',
  'Rating': 'One',
  'Price': '£23.88',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/55/33/553310a7162dfbc2c6d19a84da0df9e1.jpg'},
 {'Title': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Rating': 'One',
  'Price': '£37.59',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/09/a3/09a3aef48557576e1a85ba7efea8ecb7.jpg'},
 {'Title': 'Libertarianism for Beginners',
  'Rating': 'Two',
  'Price': '£51.33',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/0b/bc/0bbcd0a6f4bcd81ccb1049a52736406e.jpg'},
 {'Title': "It's Only the Himalayas",
  'Rating': 'Two',
  'Price': '£45.17',
  'Stok': 'In stock',
  'Link Image': 'https://books.toscrape.com/media/cache/27/a5/27a53d0bb95bdd88288eaf66c9230d7e.jpg'}]

In [37]:
#testing running run_pipeline 1 page
df = run_pipeline(1)
df

2026-10-22 06:14:00,956 | book_scraper | INFO | Selesai halaman 1. Total 20 buku
2026-10-22 06:14:01,458 | book_scraper | INFO | Semua buku telah di-scraping. Total 20 buku

,Title,Rating,Price,Stok,Link Image
0,A Light in the Attic,3,51.77,In stock,https://books.toscrape.com/media/cache/2c/da/2...
1,Tipping the Velvet,1,53.74,In stock,https://books.toscrape.com/media/cache/26/0c/2...
2,Soumission,1,50.10,In stock,https://books.toscrape.com/media/cache/3e/ef/3...
3,Sharp Objects,4,47.82,In stock,https://books.toscrape.com/media/cache/32/51/3...
4,Sapiens: A Brief History of Humankind,5,54.23,In stock,https://books.toscrape.com/media/cache/be/a5/b...
5,The Requiem Red,1,22.65,In stock,https://books.toscrape.com/media/cache/68/33/6...
6,The Dirty Little Secrets of Getting Your Dream...,4,33.34,In stock,https://books.toscrape.com/media/cache/92/27/9...
7,The Coming Woman: A Novel Based on the Life of...,3,17.93,In stock,https://books.toscrape.com/media/cache/3d/54/3...
8,The Boys in the Boat: Nine Americans and Their...,4,22.60,In stock,https://books.toscrape.com/media/cache/66/88/6...
9,The Black Maria,1,52.15,In stock,https://books.toscrape.com/media/cache/58/46/5...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",2,13.99,In stock,https://books.toscrape.com/media/cache/be/f4/b...
11,Shakespeare's Sonnets,4,20.66,In stock,https://books.toscrape.com/media/cache/10/48/1...
12,Set Me Free,5,17.46,In stock,https://books.toscrape.com/media/cache/5b/88/5...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,5,52.29,In stock,https://books.toscrape.com/media/cache/94/b1/9...
14,Rip it Up and Start Again,5,35.02,In stock,https://books.toscrape.com/media/cache/81/c4/8...
15,Our Band Could Be Your Life: Scenes from the A...,3,57.25,In stock,https://books.toscrape.com/media/cache/54/60/5...
16,Olio,1,23.88,In stock,https://books.toscrape.com/media/cache/55/33/5...
17,Mesaerion: The Best Science Fiction Stories 18...,1,37.59,In stock,https://books.toscrape.com/media/cache/09/a3/0...
18,Libertarianism for Beginners,2,51.33,In stock,https://books.toscrape.com/media/cache/0b/bc/0...
19,It's Only the Himalayas,2,45.17,In stock,https://books.toscrape.com/media/cache/27/a5/2...

In [34]:
# Cek Sampling Link Image
df[df['Title'] == 'Soumission']['Link Image'].iloc()[0] #pakai .iloc()[0] agar hasilnya tidak terpotong

'https://books.toscrape.com/media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg'

In [35]:
df

,Title,Rating,Price,Stok,Link Image
0,A Light in the Attic,3,51.77,In stock,https://books.toscrape.com/media/cache/2c/da/2...
1,Tipping the Velvet,1,53.74,In stock,https://books.toscrape.com/media/cache/26/0c/2...
2,Soumission,1,50.10,In stock,https://books.toscrape.com/media/cache/3e/ef/3...
3,Sharp Objects,4,47.82,In stock,https://books.toscrape.com/media/cache/32/51/3...
4,Sapiens: A Brief History of Humankind,5,54.23,In stock,https://books.toscrape.com/media/cache/be/a5/b...
5,The Requiem Red,1,22.65,In stock,https://books.toscrape.com/media/cache/68/33/6...
6,The Dirty Little Secrets of Getting Your Dream...,4,33.34,In stock,https://books.toscrape.com/media/cache/92/27/9...
7,The Coming Woman: A Novel Based on the Life of...,3,17.93,In stock,https://books.toscrape.com/media/cache/3d/54/3...
8,The Boys in the Boat: Nine Americans and Their...,4,22.60,In stock,https://books.toscrape.com/media/cache/66/88/6...
9,The Black Maria,1,52.15,In stock,https://books.toscrape.com/media/cache/58/46/5...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",2,13.99,In stock,https://books.toscrape.com/media/cache/be/f4/b...
11,Shakespeare's Sonnets,4,20.66,In stock,https://books.toscrape.com/media/cache/10/48/1...
12,Set Me Free,5,17.46,In stock,https://books.toscrape.com/media/cache/5b/88/5...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,5,52.29,In stock,https://books.toscrape.com/media/cache/94/b1/9...
14,Rip it Up and Start Again,5,35.02,In stock,https://books.toscrape.com/media/cache/81/c4/8...
15,Our Band Could Be Your Life: Scenes from the A...,3,57.25,In stock,https://books.toscrape.com/media/cache/54/60/5...
16,Olio,1,23.88,In stock,https://books.toscrape.com/media/cache/55/33/5...
17,Mesaerion: The Best Science Fiction Stories 18...,1,37.59,In stock,https://books.toscrape.com/media/cache/09/a3/0...
18,Libertarianism for Beginners,2,51.33,In stock,https://books.toscrape.com/media/cache/0b/bc/0...
19,It's Only the Himalayas,2,45.17,In stock,https://books.toscrape.com/media/cache/27/a5/2...